import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "@/lib/styleRegistry";
import { GlobalStyle } from "@/styles/GlobalStyle";
import RecoilProvider from "@/lib/RecoilProvider";
import ReactQueryProvider from "@/lib/ReactQueryProvider";
import Modal from "@/components/modal/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ko">
            <body className={inter.className}>
                <RecoilProvider>
                    <ReactQueryProvider>
                        <StyledComponentsRegistry>
                            <GlobalStyle />
                            {children}
                            <Modal />
                        </StyledComponentsRegistry>
                    </ReactQueryProvider>
                </RecoilProvider>
            </body>
        </html>
    );
}
